/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class gui_base */

#ifndef _Included_gui_base
#define _Included_gui_base
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gui_base
 * Method:    create_obj
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_gui_1base_create_1obj
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gui_base
 * Method:    login
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gui_1base_login
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     gui_base
 * Method:    send_msg
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_gui_1base_send_1msg
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     gui_base
 * Method:    recv_msg
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gui_1base_recv_1msg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gui_base
 * Method:    recv_history
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gui_1base_recv_1history
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gui_base
 * Method:    recv_online_user
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gui_1base_recv_1online_1user
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gui_base
 * Method:    file_send
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_gui_1base_file_1send
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     gui_base
 * Method:    file_path_set
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_gui_1base_file_1path_1set
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     gui_base
 * Method:    send_msg_to
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gui_1base_send_1msg_1to
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     gui_base
 * Method:    delete_account
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gui_1base_delete_1account
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     gui_base
 * Method:    reset_passwd
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gui_1base_reset_1passwd
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
